import Link from "next/link";
import Image from "next/image";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#050705] px-6 py-16">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="inline-flex items-center gap-2 mb-10">
          <Image
            src="/images/logo.png"
            alt="Schiddle"
            width={96}
            height={28}
            className="h-6 w-auto object-contain"
          />
        </Link>

        <h1 className="font-heading text-3xl font-bold text-white mb-2">
          Terms of Service
        </h1>
        <p className="text-schiddle-400/60 text-sm mb-10">
          Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </p>

        <div className="space-y-8 text-schiddle-200/80 leading-relaxed">
          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Acceptance of terms
            </h2>
            <p>
              By using Schiddle, you agree to these terms. If you don't agree,
              please don't use the app.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              What Schiddle does
            </h2>
            <p>
              Schiddle takes free-text schedule descriptions and uses an AI
              model to generate an organized, optimized schedule, which you
              can export as a calendar file or add to Google Calendar. See our{" "}
              <Link href="/privacy" className="text-schiddle-400 underline hover:text-schiddle-300">
                Privacy Policy
              </Link>{" "}
              for details on how your data is handled.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              No guarantee of accuracy
            </h2>
            <p>
              Schedules are generated by an AI model and may contain errors,
              incorrect times, or misinterpreted details. Schiddle is a
              planning aid, not a substitute for double-checking your own
              commitments. We are not responsible for missed events,
              scheduling conflicts, or other consequences of relying on
              AI-generated output without review.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Your responsibilities
            </h2>
            <p>
              You agree to use Schiddle only for lawful purposes, and not to
              use it to process information belonging to others without their
              knowledge or consent. You're responsible for reviewing any
              schedule or calendar event before relying on it.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Third-party services
            </h2>
            <p>
              Schiddle relies on third-party services (Groq for AI processing,
              Google for optional calendar integration). Your use of those
              integrations is also subject to their respective terms of
              service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Changes to the service
            </h2>
            <p>
              Schiddle is provided "as is," under active development, and may
              change, be interrupted, or be discontinued at any time without
              notice.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Limitation of liability
            </h2>
            <p>
              To the fullest extent permitted by law, Schiddle and its
              developers are not liable for any indirect, incidental, or
              consequential damages arising from your use of the app.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-white mb-2">
              Contact
            </h2>
            <p>
              Questions about these terms can be sent to{" "}
              
                <a href="mailto:chimdiikechukwu00@gmail.com"
                className="text-schiddle-400 underline hover:text-schiddle-300"
              >
                chimdiikechukwu00@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
